# NumPy Arrays

In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.4092981 , 0.0993631 , 0.4086647 , 0.0038015 , 0.95529754])

In [20]:
np.random.rand(5,5)

array([[0.73671537, 0.86551255, 0.79399781, 0.96208704, 0.76681591],
       [0.87149013, 0.58734585, 0.98089407, 0.90875502, 0.36893568],
       [0.60047514, 0.3383353 , 0.00511661, 0.22842177, 0.69590897],
       [0.03920445, 0.2010793 , 0.48694476, 0.96313852, 0.71463281],
       [0.40344578, 0.00573873, 0.33542998, 0.30662541, 0.85682122]])

In [22]:
np.random.randn(4,4)

array([[ 1.16597894, -2.47859696, -0.25667941, -1.18711578],
       [ 0.9200989 , -1.42677324, -0.86637413, -0.0384392 ],
       [ 0.29050817, -0.20197939, -1.38376488, -0.62247611],
       [-2.00369793, -0.75030866, -0.36673295,  2.10954184]])

In [24]:
np.random.randint(1,100,10)

array([42, 18, 27,  5,  1, 69, 44, 50, 81, 85])

In [26]:
arr=np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint(0,50,10)

In [30]:
ranarr

array([ 4, 10, 47, 27, 32,  2, 41, 30, 17, 27])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([ 4, 10, 47, 27, 32,  2, 41, 30, 17, 27])

In [34]:
ranarr.max()

47

In [35]:
ranarr.min()

2

In [36]:
ranarr.argmax()

2

In [37]:
ranarr.argmin()

5

In [38]:
arr.shape

(25,)

In [42]:
arr=arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr=np.arange(0, 11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr=arr[0:6]

In [54]:
slice_of_arr[:]=199

In [55]:
slice_of_arr

array([199, 199, 199, 199, 199, 199])

In [56]:
arr

array([199, 199, 199, 199, 199, 199,   6,   7,   8,   9,  10])